name: Generate Snake

on:
  schedule: # jalan otomatis tiap hari
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: rifaldomalau
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate Contribution Snake"
          add: "dist/github-contribution-grid-snake.svg"
